### ISSUE TITLE
Some tweaks

### ISSUE THREAD

**Issue by sorgelig** [MiSTer-devel/InputTest_MiSTer#1]
* Add holding of some button (like A) while triggering an Easter Egg. I always unintentionally trigger the game while testing the joystick which is annoying.

* Please add compiled hex files, so core can be compiled without requirement of platform specific compiler and scripts if only HDL change is required.

**Comment by sorgelig** [comment]
btw, would be good to add mouse and keyboard tests

**Comment by JimmyStones** [comment]
@sorgelig Sorry, didn't have notifications on so never saw these arrive!

I've got a new version in the works that covers all of this I think, but got distracted by holiday and the hiscore autosave stuff so will be getting back to it soon.
