### ISSUE TITLE
Core is potentially mishandling 9-bit mouse deltas

### ISSUE THREAD

**Issue by garyjsweet** [MiSTer-devel/InputTest_MiSTer#14]
I was seeing odd behaviour with my trackball and spinner in the input tester core and missile command.
It looks like an overflow issue, as moving quickly when at the edge of the screen can cause the cursor to jump in the opposite direction.

I originally tweaked Main_MiSTer to work around the issue (by clamping mouse deltas to -127 to 127) - see https://github.com/MiSTer-devel/Main_MiSTer/pull/765

Discussion with sorgelig on that PR leads me to believe that the actual problem may actually be the core not handling 9-bit signed deltas correctly. 9-bit deltas can occur even if the USB mouse can only produce 8-bit ones as multiple events can accumulate in the top-level mouse handling code before handing to the core.

Missile command shows the same anomolies, which makes it very difficult to play using a fast moving trackball.

**Comment by garyjsweet** [comment]
Looking at the code base I can see at least one issue in ps2.c:

`handle_ps2()` is ignoring the sign bits from `ps2_mouse[0]` (bits 4 & 5). It just uses `ps2_mouse[1]` and `ps2_mouse[2]` directly. This only works if the mouse deltas are in the range -127 to 127.  It really needs to build a 9-bit signed value using the sign-bit and the x/y byte. Note: the byte is not a magnitude, it's just the lower 8-bits of the 2's complement 9-bit value.

**Comment by JimmyStones** [comment]
@garyjsweet sorry about the delay!  Had a bit of trial and error to do and it sucks time at 6 mins per compile :)

Try this one and let me know if it is working any better:
https://github.com/JimmyStones/InputTest_MiSTer/blob/update/releases/InputTest_20230406.rbf

**Comment by garyjsweet** [comment]
> @garyjsweet sorry about the delay!

That's really not much of a delay, it's not an urgent problem and we all have other lives to live. I have a long weekend of decorating to look forward too :-(

> Had a bit of trial and error to do and it sucks time at 6 mins per compile :)

I can't even make the C code compile, so you're doing better than me,

> Try this one and let me know if it is working any better: https://github.com/JimmyStones/InputTest_MiSTer/blob/update/releases/InputTest_20230406.rbf

Yes, and no. The overflow problem is much, much better, though it will still jump back just a few units at the edges if you try hard enough (as will missile command). The bigger issue now though is that the mouse cursor isn't visible at all.

**Comment by JimmyStones** [comment]
Bit weird, I can definitely see the mouse pointer - did notice that I hadn't fully constrained it's position to the screen though so maybe you had just jumped out of bounds.  Try this one:

https://github.com/JimmyStones/InputTest_MiSTer/blob/update/releases/InputTest_20230407.rbf

**Comment by garyjsweet** [comment]
Ok, so I can now see the cursor (at times). If I roll far enough right the cursor reappears on the left but has changed to a crosshair instead of an arrow.

Video of what I'm seeing [here](https://1drv.ms/v/s!AgZXmGPNWbCKj_dGbjr8KMBEcoKn3A?e=UoYxqR)

**Comment by JimmyStones** [comment]
Oof, the other thing I didn't notice is that I hadn't committed the latest release properly so you got the previous build which wasn't constrained properly :D 

I've rewritten history so please try this new version of the same file!

https://github.com/JimmyStones/InputTest_MiSTer/blob/update/releases/InputTest_20230407.rbf

**Comment by garyjsweet** [comment]
Sadly we're back to having no cursor at all on this version.

**Comment by JimmyStones** [comment]
Baffling, seem to be having some problems with my source control (or my brain :D) - try this:

https://github.com/JimmyStones/InputTest_MiSTer/blob/update/releases/InputTest_20230408.rbf

**Comment by garyjsweet** [comment]
Looks much better, thanks. Visible mouse cursor clamped to the correct range without overflow.

Thanks for looking into this.
