### ISSUE TITLE
Alternate way to get into the menu/advanced mode

### ISSUE THREAD

**Issue by cadahl** [MiSTer-devel/InputTest_MiSTer#9]
When the MiSTer is in e.g. an arcade cabinet, the SELECT isn't necessarily mapped. Nor is there necessarily an ESC key to press. It would be great to have another way to enter the menu, e.g. using the OSD to flip a "dip switch".

**Comment by JimmyStones** [comment]
A good idea, I hadn't thought of that situation - I will add an OSD menu option, and also map the user button in case that is useful for someone.

I was planning to release an update in the near future so shouldn't be too far off :)

**Comment by JimmyStones** [comment]
This was fixed in a release a long time ago, oops!
